version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-db
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - mysql_bridge
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=mysql-db
    networks:
      - mysql_bridge
    depends_on:
      - mysql
networks:
  mysql_bridge:
    driver: bridge
