version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - mysql_bridge
networks:
  mysql_bridge:
    driver: bridge
